### ISSUE TITLE
Not visible XooSocialNetwork as modules in the backend

### ISSUE THREAD

**Issue by ghost** [XoopsModules26x/xoosocialnetwork#3]
Hello Developers,

also the modules XooSocialNetwork I wanted to test, but after uploading the module to the server in the directory /modules I, the module in the backend of Xoops in module management do not see.

Can one do something or you develop for? Thank you in advance.

**Comment by mambax7** [comment]
This is not a module, but an "extension", therefore you have to the "Extension" section in the Admin.

However, this will change in the future as they become all modules, but will have different categories, as communicated by Richard: http://xoops.org/modules/news/article.php?storyid=6727

**Comment by ghost** [comment]
Thank you for your answer, I just found everything under Extensions. I was thinking more that one in Xoops own Social Network module, but it's just an extension and you have to add a Network. Since I've been looking forward to early :)

But well, I always check everything !!
